name: Hourly Reddit Scrapper

on:
  schedule:
    - cron: "0 * * * *"
    workflow_dispatch:

jobs:
  run-scarpper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
      - run: pip install -r requirements.txt

      - name: Run Scrapper
      - run: python scrapper.py

      - name: Commit and push results
      - run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "chore: reddit trends scrapping on $(date)" || echo "No changes to commit"
            git push



